# AI Labour Market Exposure: An Empirical Analysis of the Anthropic Economic Index

### Imports and Reading Data

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [80]:
automation_vs_augmentation = pd.read_csv("data/automation_vs_augmentation.csv")
bls_employment = pd.read_csv("data/bls_employment_may_2023.csv")
task_mappings = pd.read_csv("data/onet_task_mappings.csv")
task_statements = pd.read_csv("data/onet_task_statements.csv")
soc_structure = pd.read_csv("data/SOC_Structure.csv")
wage_data = pd.read_csv("data/wage_data.csv")

### Data Understanding

In [18]:
print(f"automation_vs_augmentation shape: {automation_vs_augmentation.shape}")
print(f"bls_employment shape: {bls_employment.shape}")
print(f"task_mappings shape: {task_mappings.shape}")
print(f"task_statements shape: {task_statements.shape}")
print(f"soc_structure shape: {soc_structure.shape}")
print(f"wage_data shape: {wage_data.shape}")

automation_vs_augmentation shape: (6, 2)
bls_employment shape: (22, 2)
task_mappings shape: (3514, 2)
task_statements shape: (19530, 8)
soc_structure shape: (1596, 6)
wage_data shape: (1090, 10)

In [21]:
automation_vs_augmentation.head()

  interaction_type        pct
0        directive  22.563272
1    feedback loop  12.036303
2         learning  18.917648
3             none   2.901302
4   task iteration  25.476487

In [22]:
bls_employment.head()

                      SOC or O*NET-SOC 2019 Title  bls_distribution
0                          Management Occupations          10495770
1   Business and Financial Operations Occupations          10087830
2           Computer and Mathematical Occupations           5177400
3        Architecture and Engineering Occupations           2539660
4  Life, Physical, and Social Science Occupations           1389430

In [23]:
task_mappings.head()

                                           task_name       pct
0          act as advisers to student organizations.  0.006775
1  act as an advocate for farmers or farmers' gro...  0.002997
2  act as an intermediary in negotiations between...  0.012638
3  act as an intermediary in negotiations between...  0.011466
4  act as liaisons between clients and medical st...  0.001954

In [24]:
task_statements.head()

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,87.0,07/2014,Incumbent
1,11-1011.00,Chief Executives,8831,Appoint department heads or managers and assig...,Core,87.0,07/2014,Incumbent
2,11-1011.00,Chief Executives,8825,Analyze operations to evaluate performance of ...,Core,87.0,07/2014,Incumbent
3,11-1011.00,Chief Executives,8826,"Direct, plan, or implement policies, objective...",Core,87.0,07/2014,Incumbent
4,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,87.0,07/2014,Incumbent

In [25]:
soc_structure.head()

,Major Group,Minor Group,Broad Occupation,Detailed Occupation,Detailed O*NET-SOC,SOC or O*NET-SOC 2019 Title
0,11-0000,NaN,NaN,NaN,NaN,Management Occupations
1,NaN,11-1000,NaN,NaN,NaN,Top Executives
2,NaN,NaN,11-1010,NaN,NaN,Chief Executives
3,NaN,NaN,NaN,11-1011,NaN,Chief Executives
4,NaN,NaN,NaN,NaN,11-1011.03,Chief Sustainability Officers

In [26]:
wage_data.head()

,SOCcode,JobName,JobFamily,isBright,isGreen,JobZone,MedianSalary,JobForecast,ChanceAuto,WageGroup
0,13-2011.01,Accountants,Business and Financial Operations,True,False,4,70500.00,146000,-1.0,Accountants and Auditors
1,13-2011.00,Accountants and Auditors,Business and Financial Operations,True,False,-1,70500.00,146000,94.0,NaN
2,27-2011.00,Actors,"Arts, Design, Entertainment, Sports, and Media",False,False,2,17.54,7700,37.0,NaN
3,15-2011.00,Actuaries,Computer and Mathematical,True,False,4,102880.00,2200,21.0,NaN
4,29-1199.01,Acupuncturists,Healthcare Practitioners and Technical,True,False,5,73960.00,3400,-1.0,"Health Diagnosing and Treating Practitioners, ..."

In [34]:
automation_vs_augmentation.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   interaction_type  6 non-null      str
 1   pct               6 non-null      float64
dtypes: float64(1), str(1)
memory usage: 228.0 bytes

In [35]:
bls_employment.info()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 2 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   SOC or O*NET-SOC 2019 Title  22 non-null     str
 1   bls_distribution             22 non-null     int64
dtypes: int64(1), str(1)
memory usage: 484.0 bytes

In [36]:
task_mappings.info()

<class 'pandas.DataFrame'>
RangeIndex: 3514 entries, 0 to 3513
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   task_name  3514 non-null   str
 1   pct        3514 non-null   float64
dtypes: float64(1), str(1)
memory usage: 55.0 KB

In [37]:
task_statements.info()

<class 'pandas.DataFrame'>
RangeIndex: 19530 entries, 0 to 19529
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   O*NET-SOC Code         19530 non-null  str
 1   Title                  19530 non-null  str
 2   Task ID                19530 non-null  int64
 3   Task                   19530 non-null  str
 4   Task Type              18872 non-null  str
 5   Incumbents Responding  18872 non-null  float64
 6   Date                   19530 non-null  str
 7   Domain Source          19530 non-null  str
dtypes: float64(1), int64(1), str(6)
memory usage: 1.2 MB

In [38]:
soc_structure.info()

<class 'pandas.DataFrame'>
RangeIndex: 1596 entries, 0 to 1595
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Major Group                  23 non-null     str
 1   Minor Group                  98 non-null     str
 2   Broad Occupation             459 non-null    str
 3   Detailed Occupation          867 non-null    str
 4   Detailed O*NET-SOC           149 non-null    str
 5   SOC or O*NET-SOC 2019 Title  1596 non-null   str
dtypes: str(6)
memory usage: 74.9 KB

In [39]:
wage_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1090 entries, 0 to 1089
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SOCcode       1090 non-null   str
 1   JobName       1090 non-null   str
 2   JobFamily     1090 non-null   str
 3   isBright      1090 non-null   bool
 4   isGreen       1090 non-null   bool
 5   JobZone       1090 non-null   int64
 6   MedianSalary  1090 non-null   float64
 7   JobForecast   1090 non-null   int64
 8   ChanceAuto    1090 non-null   float64
 9   WageGroup     295 non-null    str
dtypes: bool(2), float64(2), int64(2), str(4)
memory usage: 70.4 KB

In [46]:
automation_vs_augmentation.isna().sum()

interaction_type    0
pct                 0
dtype: int64

In [48]:
bls_employment.isna().sum()

SOC or O*NET-SOC 2019 Title    0
bls_distribution               0
dtype: int64

In [49]:
task_mappings.isna().sum()

task_name    0
pct          0
dtype: int64

In [50]:
task_statements.isna().sum()

O*NET-SOC Code             0
Title                      0
Task ID                    0
Task                       0
Task Type                658
Incumbents Responding    658
Date                       0
Domain Source              0
dtype: int64

In [51]:
soc_structure.isna().sum()

Major Group                    1573
Minor Group                    1498
Broad Occupation               1137
Detailed Occupation             729
Detailed O*NET-SOC             1447
SOC or O*NET-SOC 2019 Title       0
dtype: int64

In [52]:
wage_data.isna().sum()

SOCcode           0
JobName           0
JobFamily         0
isBright          0
isGreen           0
JobZone           0
MedianSalary      0
JobForecast       0
ChanceAuto        0
WageGroup       795
dtype: int64

In [55]:
task_statements["O*NET-SOC Code"].head()

0    11-1011.00
1    11-1011.00
2    11-1011.00
3    11-1011.00
4    11-1011.00
Name: O*NET-SOC Code, dtype: str

In [56]:
soc_structure["Major Group"].head()

0    11-0000
1        NaN
2        NaN
3        NaN
4        NaN
Name: Major Group, dtype: str

### Merging O*NET-SOC Code with Major Group

In [77]:
# Clean soc_structure by dropping all NaN values from Major Group column
soc_structure_clean = soc_structure.dropna(subset=["Major Group"])

# Create matching key column for both tables and only take first 2 characters of each column for major occupational group
task_statements["soc_major_group"] = task_statements["O*NET-SOC Code"].str[:2]
soc_structure["soc_major_group"] = soc_structure_clean["Major Group"].str[:2]

# Join the two DataFrame's with a merge
task_occupations = task_statements.merge(
    soc_structure_clean[["soc_major_group", "SOC or O*NET-SOC 2019 Title"]],
    on="soc_major_group",
    how="left"
)

task_occupations.head()

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source,soc_major_group,SOC or O*NET-SOC 2019 Title
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,87.0,07/2014,Incumbent,11,Management Occupations
1,11-1011.00,Chief Executives,8831,Appoint department heads or managers and assig...,Core,87.0,07/2014,Incumbent,11,Management Occupations
2,11-1011.00,Chief Executives,8825,Analyze operations to evaluate performance of ...,Core,87.0,07/2014,Incumbent,11,Management Occupations
3,11-1011.00,Chief Executives,8826,"Direct, plan, or implement policies, objective...",Core,87.0,07/2014,Incumbent,11,Management Occupations
4,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,87.0,07/2014,Incumbent,11,Management Occupations

In [78]:
# Drop unnecessary columns
task_occupations = task_occupations[['O*NET-SOC Code',
                                     'Title',
                                   # 'Task ID',
                                     'Task',
                                   # 'Task Type',
                                   # 'Incumbents Responding',
                                   # 'Date',
                                   # 'Domain Source',
                                     'soc_major_group',
                                     'SOC or O*NET-SOC 2019 Title']]

task_occupations.head()

,O*NET-SOC Code,Title,Task,soc_major_group,SOC or O*NET-SOC 2019 Title
0,11-1011.00,Chief Executives,Direct or coordinate an organization's financi...,11,Management Occupations
1,11-1011.00,Chief Executives,Appoint department heads or managers and assig...,11,Management Occupations
2,11-1011.00,Chief Executives,Analyze operations to evaluate performance of ...,11,Management Occupations
3,11-1011.00,Chief Executives,"Direct, plan, or implement policies, objective...",11,Management Occupations
4,11-1011.00,Chief Executives,"Prepare budgets for approval, including those ...",11,Management Occupations

### Join Claude Usage Data to Occupations

In [73]:
task_mappings["task_name"]

0               act as advisers to student organizations.
1       act as an advocate for farmers or farmers' gro...
2       act as an intermediary in negotiations between...
3       act as an intermediary in negotiations between...
4       act as liaisons between clients and medical st...
                              ...
3509    write, design, or edit web page content, or di...
3510    write, present, and publish reports that recor...
3511    write, review, or execute plans for testing ne...
3512    write, review, or maintain engineering documen...
3513    write, update, and maintain computer programs ...
Name: task_name, Length: 3514, dtype: str

In [74]:
task_occupations["Task"]

0        Direct or coordinate an organization's financi...
1        Appoint department heads or managers and assig...
2        Analyze operations to evaluate performance of ...
3        Direct, plan, or implement policies, objective...
4        Prepare budgets for approval, including those ...
                               ...
19525    Test vessels for leaks, damage, and defects, a...
19526    Unload cars containing liquids by connecting h...
19527    Copy and attach load specifications to loaded ...
19528    Start pumps and adjust valves or cables to reg...
19529    Perform general warehouse activities, such as ...
Name: Task, Length: 19530, dtype: str

In [82]:
task_mappings["Task"] = task_mappings["task_name"].str.lower().str.strip()
task_occupations["Task"] = task_occupations["Task"].str.lower().str.strip()

task_usage = task_mappings.merge(
    task_occupations,
    on="Task",
    how="left"
)

task_usage = task_usage.drop("task_name", axis=1)
task_usage.head()

,pct,Task,O*NET-SOC Code,Title,soc_major_group,SOC or O*NET-SOC 2019 Title
0,0.006775,act as advisers to student organizations.,25-1011.00,"Business Teachers, Postsecondary",25,Educational Instruction and Library Occupations
1,0.006775,act as advisers to student organizations.,25-1021.00,"Computer Science Teachers, Postsecondary",25,Educational Instruction and Library Occupations
2,0.006775,act as advisers to student organizations.,25-1022.00,"Mathematical Science Teachers, Postsecondary",25,Educational Instruction and Library Occupations
3,0.006775,act as advisers to student organizations.,25-1031.00,"Architecture Teachers, Postsecondary",25,Educational Instruction and Library Occupations
4,0.006775,act as advisers to student organizations.,25-1032.00,"Engineering Teachers, Postsecondary",25,Educational Instruction and Library Occupations