# AI Labour Market Exposure: An Empirical Analysis of the Anthropic Economic Index

### Imports and Reading Data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import seaborn as sns

# pd.set_option("max_columns", 200)

In [2]:
job_exposure = pd.read_csv("data/job_exposure.csv")
task_penetration = pd.read_csv("data/task_penetration.csv")

In [3]:
job_exposure.head()

  occ_code                                title  observed_exposure
0  11-1011                     Chief Executives             0.0333
1  11-1021      General and Operations Managers             0.1378
2  11-1031                          Legislators             0.0000
3  11-2011  Advertising and Promotions Managers             0.1731
4  11-2021                   Marketing Managers             0.3195

In [6]:
task_penetration.head()

                                                task  penetration
0  Accept and check containers of mail from large...          0.0
1  Accept and check containers of mail or parcels...          0.0
2  Accept credit applications and verify credit r...          0.0
3           Accept music requests from event guests.          0.0
4  Accept payment from customers, and make change...          0.0

In [7]:
job_exposure.shape

(756, 3)

In [8]:
task_penetration.shape

(17998, 2)